# Generated by Django 5.2 on 2025-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventslist_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
    ]
