# Generated by Django 5.2 on 2025-06-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventslist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='indoorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoorimg', models.ImageField(blank=True, null=True, upload_to='indoorimg')),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventLists', to='events.eventslist')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenTypes', to='events.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='outdoorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdoorimg', models.ImageField(blank=True, null=True, upload_to='outdoorimg')),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventlists', to='events.eventslist')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventypes', to='events.eventtype')),
            ],
        ),
    ]
