# Generated by Django 5.2 on 2025-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtype_indoorimages_outdoorimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='non_veg_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='veg_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.TextField()),
            ],
        ),
    ]
