# Generated by Django 5.2 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_non_veg_menu_veg_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCateringDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('total_people', models.PositiveIntegerField()),
                ('food_type', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10)),
                ('menu_type', models.IntegerField()),
                ('no_of_suppliers', models.PositiveIntegerField()),
                ('cake_required', models.PositiveIntegerField(help_text='0 means no cake')),
                ('welcome_drinks', models.BooleanField(default=False)),
                ('welcome_chats', models.BooleanField(default=False)),
                ('pan', models.BooleanField(default=False)),
            ],
        ),
    ]
