# Generated by Django 5.2 on 2025-06-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_finalcateringdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10)),
            ],
        ),
    ]
