# Generated by Django 5.2 on 2025-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_extramenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_veg_menu',
            name='menu_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg_menu',
            name='menu_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
