# Generated by Django 5.2 on 2025-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_non_veg_menu_menu_number_veg_menu_menu_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
