# Generated by Django 5.2 on 2025-06-18 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_package_price', models.FloatField()),
                ('menu_price', models.FloatField()),
                ('total_menu_price', models.FloatField()),
                ('cake_price', models.FloatField()),
                ('supplier_price', models.FloatField()),
                ('maintenance_charge', models.FloatField()),
                ('cleaning_charge', models.FloatField()),
                ('gst', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catering_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_summary', to='events.finalcateringdetails')),
            ],
        ),
    ]
